services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rightfix
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    image: backend
    build:
      context: .
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: rightfix
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - 8080:8080

volumes:
  pgdata: