services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rightfix
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 54321:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: